### ISSUE TITLE
meteor-jsdoc destroys our original meteor-app

### ISSUE THREAD

**Issue by Rubinum** [fabienb4/meteor-jsdoc#32]
I've got a project with meteor and tried to build a documentation with this tool.
I followed the instructions except for that part, where you create a new project with `meteor create myproject` , because a got one which should be documented.
After setting my options in the jsdoc-conf.json and jsdoc.json I did this:
 `meteor-jsdoc build
meteor-jsdoc start`

Now I can access a documentation of my code on http://localhost:3333 **BUT** if I now go back to my normal meteor project with http://localhost:3000 the whole site is messed up with fragments of the documentation html. Why did this happen and how do I revert that? My workaround was to set the whole project back with git and that is not a way how this doc tool should work. Besides that, I included and excluded some files, which I don't want in the docs. This tool completely ignors my json-conf.json and the other file and parses through everything. Is this intended? Am I doing something completely wrong?

**Comment by Rubinum** [comment]
Now I know why my bug happens:

When I set the jsdoc.json like following:

```
{
  // Execute meteor-jsdoc in debug mode to track down errors.
  "debug": false,
  // node.js install path, default to: "`which node`" on Mac and Linux, "`where node`" on Windows
  "nodePath": "",
  // Project docs path
  "docsPath": "../docs",
  // Project docs Meteor server port, default to: 3333
  "meteorPort": 3333,
  // Copy the Meteor docs server before building the docs (required for the first build)
  // Setting this to false after the first build allows you to customize the docs templates
  // without seeing your changes overwritten the next time you build the docs.
  "initMeteor": true,
  // Update Meteor without overwriting your changes to the docs templates.
  "updateMeteor": true,
  // Add a preamble to your project's docs that will appear at the top of the docs.
  "preamble": true,
  // Link to the project repository (used to construct the file path in the docs). Optional.
  "projectRepo": "http://gitlab....",
  // Values to be used in the `<head>` for the docs.
  "docsConfig": {
    "title": "Meteor Project Docs",
    "metas": {
      "description": "Documentation for a meteor project."
    }
  }
}
```

... the problem with my original application, that the html is messed up etc, is gone.
**That means, if you set the "docsPath" to a place inside of the meteor project, which you want to document, the project itself will be messed up with some html fragments of the docs. So you must  deploy the docs outside of the folder of the project to avoid that destruction.**

I am new to meteor, but I think there are some interferrence between this tool and the meteor render engine or whatever.

**Comment by fabienb4** [comment]
Sorry to hear you are having troubles!
Configuration is everything with this tool, a small error and everything can break down, this is specially true with paths configuration.

`jsdoc-conf.json` should allow you to include or exclude paths in the `source.exclude` and `source.include` (see [JSDoc configuration - Specifying input files](http://usejsdoc.org/about-configuring-jsdoc.html#specifying-input-files)).
These files/folders will be excluded in the docs building process. _Just to be clear, they will NOT be ignored by Meteor._
The configurations inside `jsdoc-conf.json` are passed directly to `jsdoc`. `meteor-jsdoc` do not modify them in any way.

If your `docsPath` folder is located inside the meteor project's folder, it will inevitably create problems, as you will have a meteor project inside a meteor project (as said in the [README](https://github.com/fabienb4/meteor-jsdoc#config-file)).
Although it works with packages, because you have no meteor instance inside the package, with projects, it will not work well at all.
_A workaround is to use a `.` folder for your `docsPath` folder, as meteor ignore those (`.docs` instead of `docs` for example). This way, you will be able to put the docs inside the meteor project. However, you may still encounter problems, on top of my head, I can think of one, the `meteor-jsdoc stop` command, which will without a doubt kill not only the Mongo database associated with the docs, but also the one associated with the project (due to the way it detects the Meteor/Mongo instances)._

I do not recommend using a path inside the main meteor project for your docs. Doing so will create problems that can be easily avoided just using a different folder.

**Comment by Rubinum** [comment]
Thank you for this quick answer :). I would suggest, that you highlight the sentence "Do not deploy the docs in YOUR project, because it breaks your application." in the README.md. I now know it is totaly normal because a meteor project in a meteor project doesnt work, but especially for newbies it is not clear.
