### ISSUE TITLE
What if you have an angular project?

### ISSUE THREAD

**Issue by sferoze** [fabienb4/meteor-jsdoc#38]
I am using this package on an angular project. Seems like a lot of the syntax is for Blaze and Meteor server methods. 

Do I just use the `@summary` key for angular stuff? How would I use this with angular, any recommendations?

**Comment by fabienb4** [comment]
There are specific ways to document Blaze templates, and Meteor server methods, because they use special syntax.
However, you can use JSDoc to document anything in your code; as long as you use `@summary`, it will show up in your docs.
Please refer to [JSDoc documentation](http://usejsdoc.org/) for more information.
I don't use angular, so I wouldn't be of any help if there is special syntax, but I'm pretty sure commenting the code would be just like any other JS codebase.
