### ISSUE TITLE
Now that free meteor hosting is going away...

### ISSUE THREAD

**Issue by mizzao** [fabienb4/meteor-jsdoc#39]
Could we consider using adapting this to build for something like https://readthedocs.org/ ?

The docs don't really use any of the reactive features of Meteor so requiring a Meteor app is a bit heavyweight. Additionally using something like RTD could support auto-builds of documentation on checkin, which could be very useful for an OSS Meteor app.

Any thoughts?

**Comment by fabienb4** [comment]
That's a great idea, but I think it would be better to do that in a different package. It would require a complete rewrite anyway...

I wasn't really targeting Meteor free hosting when I created the package, I was thinking more about developers, and how they would be able to host the docs internally without any 3rd party (Meteor is already be installed because they are developing their apps/packages).

I am still maintaining `meteor-jsdoc`, however I no longer have time to maintain multiple gits. But you have a good idea there, so why not go ahead and build something? Feel free to use anything from this package to do so!
